name: vesper
description: "Strengthen your bond with Vesper, a beautiful app designed to nurture couple wellness with intimate features, all wrapped in a warm, modern design that feels just like home."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  crypto: ^3.0.0
  qr_flutter: ^4.0.0
  image_picker: '>=1.1.2'
  local_auth: ^2.0.0
  uuid: ^4.0.0
  intl: 0.20.2
  shared_preferences: ^2.0.0
  supabase_flutter: '>=1.10.0'
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  provider: ^6.1.2
  go_router: ^16.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/dreamflow_icon.jpg
  remove_alpha_ios: true
